### PR TITLE
fix(client): PodMeEpisode from_json → from_dict

### PR DESCRIPTION
**Pull request by mathiazom**
Not sure if this version of `podme_api` is WIP, but sharing a fix I needed for `pasjonsfrukt` 🤗

### CODE REVIEW

**Comment by bendikrb** [comment]
Thanks! Yes, it's most definitely WIP as of right now. Currently writing tests for the entire client class 👍
Speaking of; are you refactoring pasjonsfrukt to async? (I'm thinking of putting in a legacy sync alternative).

**Comment by mathiazom** [comment]
> Thanks! Yes, it's most definitely WIP as of right now. Currently writing tests for the entire client class 👍 Speaking of; are you refactoring pasjonsfrukt to async? (I'm thinking of putting in a legacy sync alternative).

Nice :+1: 

Yes, pasjonsfrukt is now updated to use the async methods. Now I'm just trying to iron out the bugs preventing the core functionality. Schibsted auth throttling is a pain 😅

**Comment by bendikrb** [comment]
> Yes, pasjonsfrukt is now updated to use the async methods.

Awesome 👍

> Now I'm just trying to iron out the bugs preventing the core functionality. Schibsted auth throttling is a pain 😅

Really? What's your experience..? I hammered quite hard last night while building the new auth flow, and didn't run in to any throttling issues at all 🤔

**Comment by mathiazom** [comment]
> Really? What's your experience..? I hammered quite hard last night while building the new auth flow, and didn't run in to any throttling issues at all 🤔

Hmm, strange. I just got a `Forbidden` response from time to time. When attempting to login from the browser with the same account, it just said something like "try again in 5 minutes". So not terrible throttling considering this will run like once every hour, but not great for development. Seems like you were luckier though 🤔

**Comment by mathiazom** [comment]
Closing this since you seem to have fixed this in the latest version 🤗

**Pull request closed without merging**
